# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7240c6ffc2c1242806756050a3e554b0bd7739a64bc1cade3e6905f4f31adc11061a9fe2a7a65850b64aad8ab621bb3c9ef164676fee8ef7712d34924584d316

test:
  secret_key_base: 7240c6ffc2c1242806756050a3e554b0bd7739a64bc1cade3e6905f4f31adc11061a9fe2a7a65850b64aad8ab621bb3c9ef164676fee8ef7712d34924584d316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>